#logging:
#    file: C:\\Users\\Asche\\log.txt

mybatis:
  #  config-location: classpath:mybatis/mybatis-cofig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=GMT%2B8
    username: root
    password: 123456
    initialization-mode: never
  #    schema: classpath:schema.sql
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #  cache:
  #    type: redis
  servlet:
    multipart:
      max-request-size: 12800KB
      max-file-size: 12800KB
#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9300
#      cluster-name: XE
#      properties:
#        data: C:\Users\Asche\ZZZ_dependencies\elasticsearch-7.2.0\data
#        logs: C:\Users\Asche\ZZZ_dependencies\elasticsearch-7.2.0\logs
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging.level.com.article.articlemanagesystem.mapper: debug
Loggers:
  Root:
    level: debug